server:
  port: 80

spring:
  datasource:
    url: jdbc:h2:mem:statements
    username: sa
    password: pwd19
    driverClassName: org.h2.Driver
  liquibase:
    changeLog: classpath:liquibase/db.changelog-master.xml
    enabled: true
