server:
  port: 80
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/postgres
    #    username: postgres
    #    password: postgres
    #    driverClassName: org.postgresql.Driver
    url: jdbc:h2:mem:statements
    username: sa
    password: pwd19
    driverClassName: org.h2.Driver
  liquibase:
    changeLog: classpath:liquibase/db.changelog-master.xml
    enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
